spring:
  profiles:
    active: local
  liquibase:
    change-log: classpath:db\changelog\db.changelog-master.yaml
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher